"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { FormField, FormSelect } from "@/components/ui/form-field";

interface LogisticsItem { id: string; campId: string; camp: { name: string }; itemName: string; quantity: number; reservedQuantity: number; damagedQuantity: number; minimumQuantity: number; unit: string; status: string; notes: string | null; }
interface Camp { id: string; name: string; }

export default function LogisticsPage() {
	const [items, setItems] = useState<LogisticsItem[]>([]); const [camps, setCamps] = useState<Camp[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showModal, setShowModal] = useState(false); const [movementItem, setMovementItem] = useState<LogisticsItem | null>(null); const [movementAction, setMovementAction] = useState("RECEIPT"); const [movementQuantity, setMovementQuantity] = useState(""); const [movementReason, setMovementReason] = useState("");
	const [formData, setFormData] = useState({ campId: "", itemName: "", quantity: "", unit: "", minimumQuantity: "", notes: "" });
	const loadData = useCallback(() => fetch("/api/logistics").then((res) => res.json()).then((data) => { if (data.success) setItems(data.data); else setError(data.message ?? "Gagal memuat data"); }).catch(() => setError("Terjadi kesalahan")).finally(() => setLoading(false)), []);
	useEffect(() => { loadData(); fetch("/api/public/camps").then((res) => res.json()).then((data) => { if (data.success) setCamps(data.data); }).catch(() => {}); }, [loadData]);
	const handleCreate = async () => { try { const res = await fetch("/api/logistics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...formData, quantity: Number(formData.quantity), minimumQuantity: Number(formData.minimumQuantity || 0) }) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.message); setShowModal(false); setFormData({ campId: "", itemName: "", quantity: "", unit: "", minimumQuantity: "", notes: "" }); loadData(); } catch (createError) { setError(createError instanceof Error ? createError.message : "Terjadi kesalahan"); } };
	const handleMovement = async () => { if (!movementItem) return; try { const res = await fetch(`/api/logistics/${movementItem.id}/movements`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: movementAction, quantity: Number(movementQuantity), reason: movementReason }) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.message); setMovementItem(null); setMovementQuantity(""); setMovementReason(""); loadData(); } catch (movementError) { setError(movementError instanceof Error ? movementError.message : "Gagal mencatat stok."); } };
	return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-xs font-bold uppercase tracking-wider text-blue-600">Inventory control</div><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Logistik</h1><p className="mt-2 text-sm text-slate-500">Kelola saldo layak pakai melalui pergerakan stok yang terlacak.</p></div><Button onClick={() => setShowModal(true)}>+ Tambah item</Button></div>{error && <Alert type="error">{error}</Alert>}{loading ? <div className="py-12 text-center text-slate-500">Memuat data logistik...</div> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200"><thead className="bg-slate-50"><tr>{["Barang", "Stok layak", "Reserved", "Rusak", "Status", "Posko", "Aksi"].map((header) => <th key={header} className="whitespace-nowrap px-5 py-3.5 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="text-sm font-semibold text-slate-900">{item.itemName}</p><p className="text-xs text-slate-500">Minimum {item.minimumQuantity} {item.unit}</p></td><td className="px-5 py-4 text-sm font-semibold text-slate-700">{item.quantity} {item.unit}<p className="text-xs font-normal text-slate-400">tersedia {item.quantity - item.reservedQuantity}</p></td><td className="px-5 py-4 text-sm text-amber-700">{item.reservedQuantity} {item.unit}</td><td className="px-5 py-4 text-sm text-rose-700">{item.damagedQuantity} {item.unit}</td><td className="px-5 py-4"><Badge label={item.status} /></td><td className="px-5 py-4 text-sm text-slate-600">{item.camp?.name}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><Button className="px-3 py-1.5" onClick={() => { setMovementItem(item); setMovementAction("RECEIPT"); }}>Stok masuk</Button><Button variant="danger" className="px-3 py-1.5" onClick={() => { setMovementItem(item); setMovementAction("DAMAGE"); }}>Rusak</Button><Button variant="secondary" className="px-3 py-1.5" onClick={() => { setMovementItem(item); setMovementAction("LOSS"); }}>Hilang</Button></div></td></tr>)}{items.length === 0 && <tr><td colSpan={7} className="px-5 py-10 text-center text-sm text-slate-500">Belum ada item logistik.</td></tr>}</tbody></table></div></div>}
		<Modal isOpen={showModal} onClose={() => setShowModal(false)} title="Tambah item logistik"><form onSubmit={(event) => { event.preventDefault(); handleCreate(); }} className="space-y-3"><FormSelect label="Posko" value={formData.campId} onChange={(value) => setFormData({ ...formData, campId: value })} options={[{ value: "", label: "Pilih posko" }, ...camps.map((camp) => ({ value: camp.id, label: camp.name }))]} required /><FormField label="Nama barang" value={formData.itemName} onChange={(value) => setFormData({ ...formData, itemName: value })} required /><FormField label="Stok awal" type="number" value={formData.quantity} onChange={(value) => setFormData({ ...formData, quantity: value })} required /><FormField label="Batas minimum" type="number" value={formData.minimumQuantity} onChange={(value) => setFormData({ ...formData, minimumQuantity: value })} /><FormField label="Unit" value={formData.unit} onChange={(value) => setFormData({ ...formData, unit: value })} placeholder="kg, dus, box" required /><FormField label="Catatan" value={formData.notes} onChange={(value) => setFormData({ ...formData, notes: value })} /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setShowModal(false)}>Batal</Button><Button type="submit">Simpan</Button></div></form></Modal>
		<Modal isOpen={Boolean(movementItem)} onClose={() => setMovementItem(null)} title={movementAction === "DAMAGE" ? "Laporkan barang rusak" : movementAction === "LOSS" ? "Catat kehilangan" : "Catat stok masuk"}>{movementItem && <form onSubmit={(event) => { event.preventDefault(); handleMovement(); }} className="space-y-3"><p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600"><b>{movementItem.itemName}</b> · tersedia {movementItem.quantity - movementItem.reservedQuantity} {movementItem.unit}</p><FormField label="Jumlah" type="number" value={movementQuantity} onChange={setMovementQuantity} required /><FormField label="Alasan / sumber" value={movementReason} onChange={setMovementReason} placeholder="Wajib untuk rusak atau kehilangan" required={movementAction !== "RECEIPT"} /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setMovementItem(null)}>Batal</Button><Button type="submit">Simpan pergerakan</Button></div></form>}</Modal>
	</div>;
}
